spring:
  datasource:
    url: xxxxxx
    username: xxxxxx
    password: xxxxxx
    driverClassName: com.sybase.jdbc4.jdbc.SybDriver

server:
  address: 0.0.0.0
  port: "8080"

logging:
  level:
    root: INFO
